WIP: Updated the code to display the shipping amount to the user in the offline mode in the price summary section (#5024)
vuestorefront/vue-storefront pull request #5037
Opened 2020-10-19 10:18 UTC by ymaheshwari1

### Related Issues
#5024

closes #

### Short Description and Why It's Useful
When we are offline, then on the checkout page the shipping amount is not displayed and the shipping amount is also not added up in the Totals.

### Screenshots of Visual Changes before/after (if There Are Any)

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2020-11-26 15:19 UTC, Fifciu requested changes

2020-11-26 15:19 UTC, Fifciu commented on core/modules/cart/helpers/calculateTotals.ts
> +  var shipping
Why `var`s?

2020-11-26 15:19 UTC, Fifciu commented on core/modules/cart/helpers/calculateTotals.ts
> +        shippingTax = shippingMethods[i].amount === 'Free' ? 0 : shippingMethods[i].amount
Where is `Free` value coming from?

2020-11-26 15:19 UTC, Fifciu commented on core/modules/cart/helpers/calculateTotals.ts
> +    for (let i = 0; i < shippingMethods['length']; i++) {
Why not `for...of`?

2021-08-31 17:17 UTC, bloodf commented
This is closed due to inactivity.

If you want your PR to be re-opened, please update your files, check for any conflicts.

If your PR is for Vue Storefront 1 target the new repository at https://github.com/vuestorefront/vue-storefront-1

2021-08-31 17:17 UTC, closed without merging