5270-Passed "serverItems" from "hookResult"
vuestorefront/vue-storefront pull request #5271
Opened 2020-12-01 17:09 UTC by bohdan-karapet

closes #
5270

### Short Description and Why It's Useful
Adding proper event payload

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2020-12-01 17:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/DivanteLtd/vue-storefront?pullRequest=5271) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/DivanteLtd/vue-storefront?pullRequest=5271) before we can accept your contribution.<br/><hr/>**Bohdan Karapet** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/DivanteLtd/vue-storefront?pullRequest=5271) it.</sub>

2020-12-02 14:43 UTC, Fifciu requested changes
Good catch! Please update changelog and we can merge it

2020-12-02 19:47 UTC, bohdan-karapet commented
Thanks @Fifciu 
Changelog was added

2021-01-07 14:27 UTC, Fifciu commented
I am rushing issues from milestone 1.12.3 in this month and I did not see this PR because of the broken link (# and 5270 are in separated lines in thread's post). That's why I've handled it on my own. I am sorry for that but please always assign a proper link to the issue in PR so I will see it

2021-01-07 14:27 UTC, closed without merging