Bugfix: Check if the variable backendPaymentMethods is iterable
vuestorefront/vue-storefront pull request #5289
Opened 2020-12-03 15:17 UTC by rozzilla

### Short Description and Why It's Useful
This is a bugfix for the "for...of" loop when the backendPaymentMethods is not iterable.
With this commit, before to enter in the loop, it checks if the variable is iterable.

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [x] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2020-12-22 11:24 UTC, Fifciu requested changes

2020-12-22 11:24 UTC, Fifciu commented on core/modules/cart/helpers/preparePaymentMethodsToSync.ts
> +  if (typeof backendPaymentMethods[Symbol.iterator] === 'function') {
Interface says it is `PaymentMethod[]` so please just check it with `Array.isArray`. This approach would be also proper and developers not familiar with Symbols, iterators, and typeof operator will understand the code.

2020-12-22 11:24 UTC, Fifciu commented on CHANGELOG.md
> +- Check if the variable backendPaymentMethods is iterable before the for...of loop - @rozzilla (#5289)
Please add a link to the PR

2020-12-22 12:05 UTC, rozzilla commented on CHANGELOG.md
> +- Check if the variable backendPaymentMethods is iterable before the for...of loop - @rozzilla (#5289)
Done it @Fifciu

2020-12-28 10:50 UTC, Fifciu approved these changes

2020-12-28 10:51 UTC, Fifciu commented
Thanks a lot @rozzilla !

2020-12-28 10:51 UTC, merged