Unify the returning properties in composables
vuestorefront/vue-storefront pull request #5330
Opened 2020-12-16 14:23 UTC by andrzejewsky

### Related Issues
closes (partially) https://github.com/DivanteLtd/vue-storefront/issues/5285

2020-12-16 14:23 UTC, andrzejewsky commented
Awaiting for: https://github.com/DivanteLtd/vue-storefront/pull/5299

2020-12-18 10:32 UTC, filrak requested changes
Chaangelog

2020-12-21 09:57 UTC, andrzejewsky commented
Changes:
- As we are unifying naming and returning properties, we have removed `useUser.totalProducts` and `useUserOrders.totalOrders` 
- Factories `useUserFactory` and `useCartFactories` are no longer return setters, they are inside of the composables instead

2020-12-21 12:32 UTC, filrak approved these changes

2020-12-21 16:02 UTC, merged