Change return statement for factories
vuestorefront/vue-storefront pull request #5350
Opened 2020-12-23 09:16 UTC by andrzejewsky

Unify the returning statements for the following core factories:
- useUserBillingFactory
- useShippingBillingFactory
- useWishlistFactory + put setter inside

2020-12-23 09:29 UTC, filipsobol approved these changes

2020-12-27 10:31 UTC, filrak requested changes
docs ;)

2020-12-28 08:58 UTC, andrzejewsky commented
@filrak internal change, there is no mention about it in the docs at the moment

2020-12-28 11:58 UTC, filrak approved these changes

2020-12-28 11:58 UTC, merged