Changing mail and password dev
vuestorefront/vue-storefront pull request #5359
Opened 2020-12-29 13:18 UTC by Fifciu

### Related Issues

closes #5315 

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [x] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [ ] No upgrade steps required (100% backward compatibility and no breaking changes)
- [x] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2020-12-29 13:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5359) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5359) before we can accept your contribution.<br/><hr/>**Fifciuu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/vue-storefront?pullRequest=5359) it.</sub>

2020-12-30 06:25 UTC, gibkigonzo commented on core/modules/user/components/UserAccount.ts
> +      this.$bus.$emit('myAccount-before-updateUser', {
How about getting out of this madness and remove event? We need to make b/c anyway.
```
async exitSection (event, updatedProfile) {
        try {
          if (updatedProfile) {
            await this.$store.dispatch('user/update', { customer: updatedProfile })
          }
          // after updating user profile we can check if we need to update password
          // we don't care if 'updatedProfile' exist or not
          if (this.changePassword && this.password) {
            // we don't need to call it twice (lines 147-148 and 188-190)
            // with that change we will keep single responsibility in `updateProfile` (only prepare object) and in `exitSection` (makes all update calls)
            this.$bus.$emit('myAccount-before-changePassword', {
              currentPassword: this.oldPassword,
              newPassword: this.password
            })
          }
          // everything is ok then get out of edit mode ('myAccount-before-changePassword' can still fail and we will not handle that :D but we would need to remove it also)
          this.remainInEditMode = false
        } catch (err) {
          this.remainInEditMode = true
          // this.$bus.$emit('myAccount-before-remainInEditMode', this.$props.activeBlock) its the same as this.remainInEditMode = true
          throw new Error(err) // or push notification
        } finally {
            this.currentUser = Object.assign({}, this.$store.state.user.current)
            this.userCompany = this.getUserCompany()
            this.changePassword = false
            this.oldPassword = ''
            this.password = ''
            this.rPassword = ''
            this.addCompany = !!this.userCompany.company // I don't know what type it has, but for sure we don't need 'if' statement here
            // this.remainInEditMode = false; I think `if (!updatedProfile) {` was needed only for this line in other scenarios we always want to set current user (updateded or not)
            this.isEdited = this.remainInEditMode // we can even go further and remove 'remainInEditMode' and use only 'isEdited':D
        }
 ```
 With that change we will remove binding with `'myAccount-before-updateUser'` and `'myAccount-before-remainInEditMode'` You also don't need to create new method `changePasswordEmit`

2020-12-30 11:42 UTC, Fifciu commented on core/modules/user/components/UserAccount.ts
> +            this.$store.dispatch('notification/spawnNotification', {
But they would need to overwrite some core method anyway to add notification

2020-12-30 15:57 UTC, gibkigonzo requested changes

2020-12-30 15:57 UTC, gibkigonzo commented on docs/guide/upgrade-notes/README.md
> +`onBeforeUpdateUser` changes signature from `(updatedProfile)` to `({ updatedProfile, callback })`. Callback is being called just after `user/update` actions sucesfully finishes.
`onBeforeUpdateUser` doesn't exist now :)

2020-12-30 15:57 UTC, gibkigonzo commented on core/modules/user/components/UserShippingDetails.ts
> -    exitSection (event, updatedShippingDetails) {
Please keep same api or add this change to upgrade notes

2021-01-05 11:29 UTC, gibkigonzo approved these changes

2021-01-05 15:08 UTC, merged