[Draft] Next: Login & Registration form error/success handling and validation
vuestorefront/vue-storefront pull request #5401
Opened 2021-01-13 07:28 UTC by lukaszjedrasik

### Related Issues

closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (if There Are Any)

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2021-01-15 09:12 UTC, filrak requested changes

2021-01-15 09:12 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/LoginModal.vue
> +          displayMessage: 'There is already an existing customer with the email.',
why you're not displaying the email here?

2021-01-15 09:12 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/LoginModal.vue
> +      const knownErrors = [
You're missing translation keys here

2021-01-15 09:12 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/LoginModal.vue
> +    const handleError = ({ email }) => {
It's worth externalizing the `knownErrors` object so it can be easily overridden by theme integrators (`theme/helpers/errors/authentication.ts`)

2021-01-15 09:12 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/LoginModal.vue
>      <transition name="sf-fade" mode="out-in">
It's not related to this particular issue but if this modal is for both login and registration perhaps it should be just `AuthModal`

2021-02-08 10:35 UTC, lukaszjedrasik commented
@filrak @andrzejewsky 

What I saw. After creating a second account with the same credential we have an infinity loader and the `customerSignMeUp` request status all the time is `pending` (on the demo page -- same)

Steps to reproduce:

1. Create an account
2. Logout
3. Create a second account with the same email / log in with the wrong credentials
4. You will see an infinity loader. After few minutes you have got Network Error

Wdyt?


https://user-images.githubusercontent.com/40273258/107207973-3f090780-6a01-11eb-97ff-f859bc8a0fa3.mp4

2021-02-15 15:57 UTC, filrak approved these changes

2021-02-15 16:04 UTC, filrak requested changes

2021-02-15 16:04 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/Auth/RegisterForm.vue
> +      serverError.value = knownErrors.find(knownError => knownError.originalMessage === currErr.message);
how about replacing both with just `getFriendlyError(i18n, message)`

2021-02-15 16:04 UTC, filrak commented on packages/core/nuxt-theme-module/theme/helpers/errors/index.js
> +import { authErrors } from './authentication';
if you're writing a function it shouldn't be named with a verb (function is doing something and name should tell what its doing), suggestion above (getFriendlyErrors) with a new signature

2021-02-15 16:04 UTC, filrak commented on packages/core/nuxt-theme-module/theme/helpers/errors/authentication.ts
> +export const authErrors = (context, email) => {
this part is integration-specific and shouldn't be a part of agnostic module

2021-02-15 16:09 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/Auth/RegisterForm.vue
> +      serverError.value = knownErrors.find(knownError => knownError.originalMessage === currErr.message);
We can even go one step further and implement this as a UI heleper so you don't have to pass context in `setup`

2021-02-16 09:37 UTC, andrzejewsky requested changes

2021-02-16 09:37 UTC, andrzejewsky commented on packages/core/nuxt-theme-module/theme/helpers/errors/authentication.ts
> +export const authErrors = (context, email) => {
wait... what??? why do you need such a mapping? use just translation keys within integration:

eg:
```
"There is already an existing customer with this email": "There is already an existing customer with this email {email}"
```

and in the code
```
$t(response.message, { email }) // vue i18n already supports interpolation
```

I know you need interpolation for the keys too, but maybe you can recognize this kind of error by using eg. an error code or something else? Clearly, look into i18n docs I'm pretty sure you can solve this

2021-04-01 10:47 UTC, closed without merging