Next: Moved the same dependencies from ct/bp to nuxt-theme-module
vuestorefront/vue-storefront pull request #5409
Opened 2021-01-14 16:05 UTC by lukaszjedrasik

### Related Issues

closes #

### Short Description and Why It's Useful
Moved the same dependencies from ct/bp to nuxt-theme-module

### Screenshots of Visual Changes before/after (if There Are Any)

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2021-01-18 08:31 UTC, filipsobol requested changes

2021-01-18 08:31 UTC, filipsobol commented on packages/boilerplate/theme/package.json
> -    "@vue-storefront/nuxt": "^2.2.0",
This shouldn't be removed

2021-01-18 08:31 UTC, filipsobol commented on packages/commercetools/theme/package.json
> -    "@vue-storefront/nuxt": "^2.2.0",
This shouldn't be removed

2021-01-18 08:31 UTC, filipsobol commented on packages/boilerplate/theme/package.json
>      "@nuxtjs/style-resources": "^1.0.0",
This can be removed, because it's a dependency of `@vue-storefront/nuxt`

2021-01-18 08:31 UTC, filipsobol commented on packages/core/nuxt-theme-module/package.json
> +    "nuxt": "^2.13.3",
This shouldn't be here, but  in templates instead.

2021-01-18 08:31 UTC, filipsobol commented on packages/core/nuxt-theme-module/package.json
> +    "@vue-storefront/nuxt": "^2.2.0"
This shouldn't be here, but in templates instead.

2021-01-18 10:24 UTC, filipsobol requested changes

2021-01-18 10:24 UTC, filipsobol commented on packages/boilerplate/theme/package.json
> -    "@vue-storefront/nuxt-theme": "^2.2.0",
This shouldn't be removed

2021-01-18 10:24 UTC, filipsobol commented on packages/commercetools/theme/package.json
> -    "@vue-storefront/nuxt-theme": "^2.2.0",
This shouldn't be removed

2021-01-18 10:24 UTC, filipsobol commented on packages/core/nuxt-theme-module/package.json
> -    "lodash.merge": "^4.6.2"
This shouldn't be removed

2021-01-18 10:24 UTC, filipsobol commented on packages/commercetools/theme/package.json
> +    "lodash.merge": "^4.6.2",
This is non needed here

2021-01-18 10:24 UTC, filipsobol commented on packages/boilerplate/theme/package.json
> +    "lodash.merge": "^4.6.2",
This is non needed here

2021-02-18 11:46 UTC, filrak commented
if this si still alid please reolve conflicts @lukaszjedrasik and ping me ;)

2021-02-18 12:49 UTC, lukaszjedrasik commented
@filrak conflicts resolved

2021-03-08 10:15 UTC, filrak approved these changes

2021-03-08 10:16 UTC, merged