Api client / composables reference docs
vuestorefront/vue-storefront pull request #5455
Opened 2021-01-27 14:44 UTC by lukaszjedrasik

### Related Issues

closes #5428 

### Short Description and Why It's Useful
I have added two commands to our `core/docs/package.json`:

- ct-api-client-gen
- ct-composables-gen

Both of them we can use for auto-generating API references. It is pretty easy but for `ct-composables-gen` we should one more extra thing. Typedoc has a problem with references in our `commercetools/composables/tsconfig.json (line 24)` so temporarily we have to get rid of this line (add it again after doc generated).

Unfortunately, we do not have full control over a created template, so if we want, we can edit it manually.

### Screenshots of Visual Changes before/after (if There Are Any)

https://user-images.githubusercontent.com/40273258/106001346-1eab8580-60b0-11eb-9488-67f7d9b859db.mp4

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature
- [ ] (Next only) I've followed this [instruction](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and I've created a `.js` file with information about my Pull Request

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2021-01-27 14:59 UTC, NataliaTepluhina commented
I wonder if it would be possible to use a generated file as a source for VuePress sidebar navigation, so we could have both table of contents and a sidebar (like [here](https://v3.vuejs.org/api/))

2021-01-27 15:27 UTC, filrak commented on packages/core/docs/commercetools/api-client-reference/modules.md
> +- [createMyOrderFromCart](modules/createmyorderfromcart.md)
where this `modules/createmyorderfromcart.md` is?

2021-01-27 15:27 UTC, filrak requested changes

2021-01-27 15:27 UTC, filrak commented on packages/core/docs/commercetools/api-composables-reference/modules.md
> +- [getters/\_utils](modules/getters__utils.md)
there should be only composables here

2021-02-09 09:46 UTC, filrak reviewed
feedback on a call

2021-02-11 15:39 UTC, lukaszjedrasik commented
@filrak ready for review

2021-02-16 15:12 UTC, filrak requested changes

2021-02-16 15:12 UTC, filrak commented on packages/core/docs/commercetools/use-product.md
> +- `products` - a main data object that contains an array of products fetched by `search` method,
missing type

2021-02-16 15:12 UTC, filrak commented on packages/core/docs/commercetools/use-product.md
> +interface ProductGetters<PRODUCT, PRODUCT_FILTER> {
use commercetools types

2021-02-16 15:12 UTC, filrak commented on packages/core/docs/commercetools/use-category.md
> +interface CategoryGetters<CATEGORY> {
use commercetools types

2021-02-17 13:46 UTC, filrak commented on packages/core/docs/commercetools/use-review.md
> +## Usage
redundant

2021-02-17 13:46 UTC, filrak commented on packages/core/docs/commercetools/use-cart.md
>  platform: Commercetools
we don't need this anymore

2021-02-17 13:46 UTC, filrak commented on packages/core/docs/commercetools/use-cart.md
> +# Cart
```suggestion
# `useCart`
```

2021-02-17 13:46 UTC, filrak commented on packages/core/docs/commercetools/use-cart.md
> +Because `cart` property is a raw response with some additional properties, it's recommended to use `cartGetters` for accessing any data from it. It includes the following helper functions:
```suggestion
```

2021-02-17 13:46 UTC, filrak commented on packages/core/docs/commercetools/use-cart.md
> +Interface for the above getter looks like this:
```suggestion
```

2021-02-17 13:46 UTC, filrak commented on packages/core/docs/commercetools/use-cart.md
> +import { useCart, cartGetters } from '@vue-storefront/commercetools';
for enterprise ones change that to `@vsf-enterprise/commercetools`

2021-02-17 13:46 UTC, filrak commented on packages/core/docs/commercetools/use-cart.md
>  :::tip
redundant

2021-02-18 13:15 UTC, filrak commented on packages/core/docs/commercetools/use-category.md
> +- `search` - a main querying function that is used to query categories from eCommerce platform and populate the `categories` object with the result. Every time you invoke this function API request is
missing parameters

2021-02-25 15:37 UTC, filrak commented on packages/core/docs/commercetools/use-facet.md
>  import { useFacet, facetGetters } from '@vue-storefront/your-integration';
```suggestion
import { useFacet, facetGetters } from '@vsf-enterprise/commercetools';
```

2021-02-25 15:38 UTC, filrak commented on packages/core/docs/commercetools/use-review.md
> +import { useReview, reviewGetters } from '@vsf-enterprise/ct-reviews';
```suggestion
import { useReview, reviewGetters } from '@vsf-enterprise/commercetoolss';
```

2021-02-25 15:39 UTC, filrak commented on packages/core/docs/commercetools/use-user-shipping.md
> +import { useUserShipping, userShippingGetters } from '@vsf-enterprise/ct-shipping';
```suggestion
import { useUserShipping, userShippingGetters } from '@vsf-enterprise/commercetools';
```

2021-02-25 15:49 UTC, filrak commented on packages/core/docs/commercetools/use-user-billing.md
> +import { useUserBilling, userBillingGetters } from '@vsf-enterprise/ct-billing';
```suggestion
import { useUserBilling, userBillingGetters } from '@vsf-enterprise/commercetools';
```

2021-02-25 15:50 UTC, filrak commented on packages/core/docs/commercetools/use-wishlist.md
> +import { useWishlist, wishlistGetters } from '@vsf-enterprise/ct-wishlist';
```suggestion
import { useWishlist, wishlistGetters } from '@vsf-enterprise/commercetools';
```

2021-02-25 15:50 UTC, filrak approved these changes

2021-02-25 15:50 UTC, merged