fixed some typo in docs
vuestorefront/vue-storefront pull request #5484
Opened 2021-02-04 08:02 UTC by lukaszjedrasik

### Related Issues

closes #

### Short Description and Why It's Useful
As we talked, I have used changes from this PR https://github.com/vuestorefront/vue-storefront/pull/5391

### Screenshots of Visual Changes before/after (if There Are Any)

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature
- [ ] (Next only) I've followed this [instruction](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and I've created a `.js` file with information about my Pull Request

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2021-02-04 09:25 UTC, Fifciu approved these changes

2021-02-04 09:26 UTC, Fifciu commented on CHANGELOG.md
> +- Fixed some typo in docs (#5071)
Please also mark yourself and @akucharczyk

2021-02-04 09:26 UTC, Fifciu requested changes
Changes requested

2021-02-04 09:34 UTC, lukaszjedrasik commented
@Fifciu fixed

2021-02-05 12:18 UTC, Fifciu approved these changes
Look great, good job

2021-02-05 12:19 UTC, merged