Removed VueObserveVisibility from core
vuestorefront/vue-storefront pull request #5544
Opened 2021-02-15 14:23 UTC by lukaszjedrasik

### Related Issues

closes #4998 

### Short Description and Why It's Useful
Remove `VueObserveVisibility` dependency from core as it's only used in the theme level.

### Screenshots of Visual Changes before/after (if There Are Any)

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature
- [ ] (Next only) I've followed this [instruction](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and I've created a `.js` file with information about my Pull Request

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2021-02-18 11:30 UTC, Fifciu requested changes
I think you should also update yarn.lock

2021-02-19 07:41 UTC, lukaszjedrasik commented
@Fifciu yarn.lock updated

2021-02-19 09:09 UTC, Fifciu requested changes

2021-02-19 09:09 UTC, Fifciu commented on core/package.json
> -    "vue-observe-visibility": "^0.4.1",
`vue-observe-visibility"` is in 2 package.json files and you removed it only in the one, why?

2021-02-19 09:09 UTC, Fifciu commented on yarn.lock
> +vue-lazyload@^1.2.6:
`vue-observe-visibility` did not disappear. Probably because of not using it from both package.json's

2021-03-09 13:51 UTC, Fifciu approved these changes

2021-03-09 13:53 UTC, merged