Quick search
vuestorefront/vue-storefront pull request #5583
Opened 2021-02-25 13:04 UTC by justyna-13

### Related Issues

closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (if There Are Any)

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [ ] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [ ] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature
- [ ] (Next only) I've followed this [instruction](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and I've created a `.js` file with information about my Pull Request

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2021-02-25 13:34 UTC, filrak requested changes

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +    const searchOpen = ref(false);
```suggestion
    const isSearchOpen = ref(false);
```

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +    const searchRef = ref(null);
```suggestion
    const searcBarhRef = ref(null);
```

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +        if (searchOpen.value) {
we can achieve that by closing the search box after search form loses focus

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +    const handleSearchInput = (input) => term.value = input;
v-model

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +    const closeSearchAndRemoveTerm = () => {
```suggestion
    const closeSearch = () => {
```

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
>      const { changeSearchTerm, getFacetsFromURL } = useUiHelpers();
changeSearchTerm => `setTermForUrl`

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
>      const { changeSearchTerm, getFacetsFromURL } = useUiHelpers();
and maybe move to the search component

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +            @input="handleSearchInput"
most likely can be just a single fn

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +      if (!isMobile.value && term.value.length > 0) {
make it a single if and maybe assign to a variable
const canDoSth = (!oldVal && newVal) || (newVal.length !== oldVal.length && searchOpen.value === false && ((!isMobile.value && term.value.length > 0))

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +        debounceSearchInput();
we don't need to externalize it

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +    const handleSearch = async (e) => {
just have a single debounced function that handles both search AND passing term to the url

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +    const handleCloseSearchButton = () => {
```suggestion
    const closeSearch = () => {
```

2021-02-25 13:34 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +      <SearchResults :visible="searchOpen" :result="result" @closeSearchResults="closeSearchAndRemoveTerm" />
closeSearchResults => close

2021-02-25 13:50 UTC, filrak reviewed
- get rid of hardcoded links/data

2021-02-25 13:50 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/SearchResults.vue
> +      title="Search results"
i18n

2021-02-25 13:50 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/SearchResults.vue
> +          <SfMegaMenuColumn title="Categories" class="sf-mega-menu-column--pined-content-on-mobile search__categories">
i18n

2021-02-25 13:50 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/SearchResults.vue
> +          <SfMegaMenuColumn title="Product suggestions" class="sf-mega-menu-column--pined-content-on-mobile search__results">
i18n

2021-02-25 13:50 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/SearchResults.vue
> +      emit('closeSearchResults');
not needed after implementing focus/close

2021-02-25 13:50 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/SearchResults.vue
> +    const toggleSearch = ref(props.visible);
```suggestion
    const isSearchOpen = ref(props.visible);
```

2021-02-25 13:50 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/SearchResults.vue
> +            <SfButton class="action-buttons__button color-secondary" @click="goToPath('/c/women/women-clothing')">See all results</SfButton>
i18n

2021-02-25 13:50 UTC, filrak commented on packages/core/nuxt-theme-module/theme/components/SearchResults.vue
> +            <SfButton class="sf-button--text see-all desktop-only" @click="goToPath('/c/women/women-clothing')">See all results</SfButton>
i18n

2021-02-27 10:42 UTC, justyna-13 commented on packages/core/nuxt-theme-module/theme/components/AppHeader.vue
> +      getSearchTermFromUrl(term.value);
```suggestion
```

2021-02-27 15:03 UTC, merged