fix: body scroll lock
vuestorefront/vue-storefront pull request #5593
Opened 2021-02-27 14:52 UTC by RakowskiPrzemyslaw

### Related Issues

closes #https://github.com/vuestorefront/vue-storefront/issues/5514

### Short Description and Why It's Useful

Removing ` overflow-x: hidden` from body fixes functionality of body-scroll-lock and hides scrollbar

### Screenshots of Visual Changes before/after (if There Are Any)

![image](https://user-images.githubusercontent.com/33127342/109390570-c10a9300-7912-11eb-8442-f68fd7355499.png)

### Which Environment This Relates To
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)

- [ ] Test version (https://test.storefrontcloud.io) - this is a new feature or improvement for Vue Storefront. I've created branch from `develop` branch and want to merge it back to `develop`
- [x] RC version (https://next.storefrontcloud.io) - this is a stabilisation fix for Release Candidate of Vue Storefront. I've created branch from `release` branch and want to merge it back to `release`
- [ ] Stable version (https://demo.storefrontcloud.io) - this is an important fix for current stable version. I've created branch from `hotfix` or `master` branch and want to merge it back to `hotfix`

### Upgrade Notes and Changelog
- [x] No upgrade steps required (100% backward compatibility and no breaking changes)
- [] I've updated the [Upgrade notes](https://github.com/DivanteLtd/vue-storefront/blob/develop/docs/guide/upgrade-notes/README.md) and [Changelog](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md) on how to port existing Vue Storefront sites with this new feature
- [x] (Next only) I've followed this [instruction](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and I've created a `.js` file with information about my Pull Request

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [ x] I read and followed [contribution rules](https://github.com/DivanteLtd/vue-storefront/blob/master/CONTRIBUTING.md)

2021-02-27 14:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/vue-storefront?pullRequest=5593) it.</sub>

2021-03-01 16:13 UTC, Fifciu requested changes
Looks fine, just fix this double space

2021-03-01 16:13 UTC, Fifciu commented on packages/core/docs/changelog/5514.js
> +  description: 'removed  overflow-x: hidden from html tag',
Please get rid of double space

2021-03-02 09:07 UTC, RakowskiPrzemyslaw commented on packages/core/docs/changelog/5514.js
> +  description: 'removed  overflow-x: hidden from html tag',
good catch, removed

2021-03-02 09:12 UTC, filrak approved these changes

2021-03-02 09:13 UTC, merged

2021-03-20 06:52 UTC, Baroshem commented
@RakowskiPrzemyslaw 

This pull request fixed a problem with checkout body scroll but added a global bug with mobile view Filip discovered yesterday. 

To solve current issue, different solution must be created and tested on all devices.

2021-03-20 20:55 UTC, RakowskiPrzemyslaw commented
@Baroshem maybe just wrapping it in media query would do the trick? What do you think?

2021-03-21 17:00 UTC, Baroshem commented
@RakowskiPrzemyslaw 
Yeah, it seems to bo working -> https://github.com/vuestorefront/vue-storefront/pull/5682/commits/fec4a5f7dac8f352b2261aa316bf611e04418587