Bug/infinite loading
vuestorefront/vue-storefront pull request #5643
Opened 2021-03-10 10:49 UTC by Baroshem

### Related Issues

closes #5508 
closes #5463 

### Short Description of the PR

Fixed problem with infinite loading caused by not having error handing in core/middleware. By implementing try catch, and throwing more accurate error in useUserFactory, now LoginModal is not closing after incorrect register/login attempt and it shows appropriate error. It also allowed to fix another problem related to empty shipping method when there was no shipping methods available.

### Screenshots of Visual Changes before/after (if There Are Any)

![image](https://user-images.githubusercontent.com/37120330/110617685-42291c00-8196-11eb-8845-439cce009404.png)

![image](https://user-images.githubusercontent.com/37120330/110617748-5240fb80-8196-11eb-983d-62889997a675.png)

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [x] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

2021-03-22 08:15 UTC, andrzejewsky requested changes

2021-03-22 08:15 UTC, andrzejewsky commented on packages/core/core/src/factories/useUserFactory.ts
> +        error.value.register = err.response?.data || err;
just `err` - you can't assume graphql in the core

2021-03-22 09:52 UTC, andrzejewsky requested changes

2021-03-22 09:52 UTC, andrzejewsky commented on packages/core/nuxt-theme-module/theme/components/LoginModal.vue
> +        const loginGraphQLErrorMessage = loginGraphQLError?.graphQLErrors[0]?.message;
same here - this is core template

2021-03-22 10:31 UTC, Baroshem commented on packages/core/nuxt-theme-module/theme/components/LoginModal.vue
> +        const loginGraphQLErrorMessage = loginGraphQLError?.graphQLErrors[0]?.message;
Moved error handling CT integration

2021-03-25 11:05 UTC, filrak approved these changes

2021-03-26 12:33 UTC, andrzejewsky approved these changes

2021-03-29 06:30 UTC, merged