[WIP] Search adjusted to EE
vuestorefront/vue-storefront pull request #5709
Opened 2021-03-25 14:47 UTC by justyna-13

### Related Issues

closes #

### Short Description of the PR

### Screenshots of Visual Changes before/after (if There Are Any)

### Pull Request Checklist

- [ ] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [ ] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [ ] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

2021-03-26 08:46 UTC, andrzejewsky requested changes

2021-03-26 08:46 UTC, andrzejewsky commented on packages/core/nuxt-theme-module/theme/components/SearchResults.vue
> -                <SfMenuItem :label="category.label" :link="`/c/women/${category.slug}`"/>
why? that won't work for the different catalogs of products

2021-03-26 08:46 UTC, andrzejewsky commented on packages/core/nuxt-theme-module/theme/components/SearchResults.vue
> +        <div v-if="searchResult.data && Object.keys(searchResult.data).length > 0" class="search__wrapper-results" key="results">
you can't assume `data` field in the core theme - it depends on the platform

2021-03-30 08:47 UTC, andrzejewsky approved these changes

2021-04-07 13:09 UTC, andrzejewsky approved these changes

2021-04-09 06:55 UTC, filrak approved these changes

2021-04-09 07:00 UTC, merged