Next: Login & Registration form error/success handling and validation
vuestorefront/vue-storefront pull request #5724
Opened 2021-04-01 11:23 UTC by lukaszjedrasik

### Related Issues

closes #5377 

### Short Description of the PR

- Added VSF Error handling to display errors in Login/Registration forms.
- Added `AuthModal` component and splitted`LoginModal` component to `LoginForm` and `RegisterForm`.
- Changed `isLoginModal` and `toggleLoginModal` to `isAuthModal` and `toggleAuthModal`

### Screenshots of Visual Changes before/after (if There Are Any)

**Desktop:**
https://user-images.githubusercontent.com/40273258/113286914-1c9eb680-92ed-11eb-9e05-5e0e87736225.mp4

**Mobile:**
https://user-images.githubusercontent.com/40273258/113286961-32ac7700-92ed-11eb-803c-aec2ad6a986c.mp4

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

2021-04-13 13:33 UTC, andrzejewsky requested changes

2021-04-13 13:33 UTC, andrzejewsky commented on packages/commercetools/theme/components/Auth/RegisterForm.vue
> +            :errorMessage="registerError && registerError.field && registerError.field === 'email' ? $t(registerError.message) : $t(errors[0])"
create computed properties for both

2021-04-13 13:33 UTC, andrzejewsky commented on packages/commercetools/theme/components/Auth/RegisterForm.vue
> +      if (registerError.value && registerError.value.code === 'DuplicateField' && registerError.value.message.search(form.value.email) !== -1) {
jeezzz, why that's sooo long? :D is it readable? can you create a function for checking this or even a computed property?

2021-04-28 10:46 UTC, andrzejewsky commented
solve conflicts please

2021-08-31 17:19 UTC, bloodf commented
This is closed due to inactivity.

If you want your PR to be re-opened, please update your files, check for any conflicts.

If your PR is for Vue Storefront 1 target the new repository at https://github.com/vuestorefront/vue-storefront-1

2021-08-31 17:19 UTC, closed without merging