Add link to product in CartSidebar
vuestorefront/vue-storefront pull request #5728
Opened 2021-04-06 06:31 UTC by igorwojciechowski

### Related Issues

closes #5726 

### Short Description of the PR

Adds link to product page in CartSidebar

### Screenshots of Visual Changes before/after (if There Are Any)

N/A
### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [x] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

2021-04-06 06:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5728) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5728) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/vue-storefront?pullRequest=5728) it.</sub>

2021-04-13 13:28 UTC, andrzejewsky approved these changes

2021-06-11 09:29 UTC, andrzejewsky requested changes
Ok according to our agreements, please create an RFC first with the proposal for a new getters in the core, link this PR, and one RFC is confirmed we can merge it

2021-08-31 17:22 UTC, bloodf commented
This is closed due to inactivity.

If you want your PR to be re-opened, please update your files, check for any conflicts.

If your PR is for Vue Storefront 1 target the new repository at https://github.com/vuestorefront/vue-storefront-1

2021-08-31 17:22 UTC, closed without merging