Bugfix for cart-tab-sync in multistore environment
vuestorefront/vue-storefront pull request #5732
Opened 2021-04-06 11:20 UTC by cewald

### Related Issues

Related to #3838 & #4083

This is a copy of #5711 rebased on `hotfix/v1.12.3` branch.
 
### Short Description of the PR

The multi-tab cart-sync feature wouldn't work in a multistore-environment with disabled `storeViews.commonCache` feature as the keys in local-storage are prefixed with the store-code like `de-shop/cart/current-cart`.

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [x] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

2021-04-06 11:27 UTC, Fifciu requested changes
Thanks for rapid reaction, I see you also refacored condition a bit which is great. Now it is much more readable. However, I have to ask you to move `checkMultistoreKey` function above `getItemsFromStorage` to respect our linter.

2021-04-06 11:31 UTC, cewald commented
Sorry, my fault – it's done.

2021-04-06 11:38 UTC, cewald commented on core/modules/cart/helpers/syncCartWhenLocalStorageChange.ts
>    const value = JSON.parse(localStorage[key])
We still need to fetch the correct key in `JSON.parse(localStorage[key])` when multistore is enabled.

2021-04-06 11:48 UTC, cewald commented on core/modules/cart/helpers/syncCartWhenLocalStorageChange.ts
>    const value = JSON.parse(localStorage[key])
I've moved it into the if-else clause.

2021-04-14 07:51 UTC, Fifciu commented
Please resolve conflict with the changelog and we could merge it

2021-04-14 09:09 UTC, Fifciu approved these changes

2021-04-14 09:09 UTC, Fifciu commented
Great job, thanks!

2021-04-14 09:09 UTC, merged