ci: add labeler config
vuestorefront/vue-storefront pull request #5800
Opened 2021-04-23 07:25 UTC by Baroshem

This PR adds labeler workflow for VSF 2 (Next) to automatically assing labels based on modified files.

2021-04-23 08:23 UTC, Fifciu requested changes
Awesome one. Just one thing to update. It would be awesome if you could also prepare similar PR for hotfix 1.12.3 and develop

2021-04-23 08:23 UTC, Fifciu commented on .github/labeler.yml
> +# Add 'core' label to any change to packages/core files within the source dir EXCEPT for the docs sub-folder
`packages/core` -> `core`

2021-04-23 08:23 UTC, Fifciu commented on .github/labeler.yml
> +commercetools:
It does not exist in vsf1

2021-04-23 08:43 UTC, Baroshem commented on .github/labeler.yml
> +# Add 'core' label to any change to packages/core files within the source dir EXCEPT for the docs sub-folder
You are right. Changed it. Thanks!

2021-04-23 08:43 UTC, Baroshem commented on .github/labeler.yml
> +commercetools:
Removed

2021-08-31 17:19 UTC, bloodf commented
This is closed due to inactivity.

If you want your PR to be re-opened, please update your files, check for any conflicts.

If your PR is for Vue Storefront 1 target the new repository at https://github.com/vuestorefront/vue-storefront-1

2021-08-31 17:19 UTC, closed without merging