update docs
vuestorefront/vue-storefront pull request #5811
Opened 2021-04-23 14:21 UTC by vn-vlad

Task: https://vsf.atlassian.net/browse/EN-164

2021-04-23 16:54 UTC, filrak requested changes

2021-04-23 16:54 UTC, filrak commented on packages/core/docs/integrate/integration-guide.md
>  const { createApiClient, integrationPlugin } = apiClientFactory({
https://github.com/vuestorefront/ecommerce-integration-boilerplate/blob/master/packages/api-client/src/index.server.ts#L15 no integration plugin, please check integration plugin's code as well

2021-04-26 09:17 UTC, andrzejewsky approved these changes

2021-04-26 09:47 UTC, andrzejewsky commented
A few more things that need to be updated

- example of plugin:

```js
import { integrationPlugin } from '@vue-storefront/core'

const moduleOptions = <%= serialize(options) %>;

export default integrationPlugin(({ app, integration }) => {
  const settings = { api: '/graphql', user: 'root' }

  integration.configure({ ...moduleOptions, ...settings })
});
```

- Extending an existing integration
just remove that section

- setup in factory params
please change it to `provide`

- Creating composables without VSF factories
- 
```js
import { vsfRef, useVSFContext } from '@vue-storefront/core';
const useCart = () => {
  const cart = vsfRef(null, 'my-own-cart')
  const context = useVSFContext();
  const addToCart = async ({ product }) => {
    return context.$ownAPI.updateCart(product)
  }
  return { addToCart, cart }
}
```

2021-04-27 11:37 UTC, andrzejewsky approved these changes

2021-04-27 11:53 UTC, merged