replace Slack links with discord links
vuestorefront/vue-storefront pull request #5825
Opened 2021-04-26 08:46 UTC by janmyszkier

### Related Issues
None

closes #

### Short Description of the PR
Replace support channel info with Discord

### Screenshots of Visual Changes before/after (if There Are Any)

### Pull Request Checklist

- [ ] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [ ] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- [ ] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

2021-04-26 08:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5825) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5825) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/vue-storefront?pullRequest=5825) it.</sub>

2021-04-26 09:27 UTC, filipsobol requested changes

2021-04-26 09:27 UTC, filipsobol commented on packages/core/docs/.vuepress/components/PersonTile.vue
> +    <div><b><a href="https://discord.vuestorefront.io">Discord:</a></b> @{{ discord }} </div>
Please remove `@`

2021-04-26 09:27 UTC, filipsobol commented on packages/core/docs/enterprise/feature-list.md
> +The Storefront Cloud team will guarantee 99,8% SLA for the infrastructure and Vue Storefront base app (modifications and custom integrations created by merchant/agency are excluded). Our clients can
Our clients have dedicated Slack channels which we use internally. Please revert this change.

2021-04-26 09:27 UTC, filipsobol commented on packages/core/docs/.vuepress/components/PersonTile.vue
> +    <div><b><a href="https://discord.vuestorefront.io">Discord:</a></b> @{{ discord }} </div>
```suggestion
    <div><b><a href="https://discord.vuestorefront.io">Discord:</a></b> {{ discord }} </div>
```

2021-04-26 09:27 UTC, filipsobol commented on packages/core/docs/commercetools/maintainers.md
> +  discord="andrzejewsky"
```suggestion
  discord="andrzejewsky#9834"
```

2021-04-26 09:27 UTC, filipsobol commented on packages/core/docs/enterprise/feature-list.md
> +The Storefront Cloud team will guarantee 99,8% SLA for the infrastructure and Vue Storefront base app (modifications and custom integrations created by merchant/agency are excluded). Our clients can
```suggestion
The Storefront Cloud team will guarantee 99,8% SLA for the infrastructure and Vue Storefront base app (modifications and custom integrations created by merchant/agency are excluded). Our clients can use our dedicated Slack support channel to contact the team and check the tickets’ statuses.
```

2021-04-26 09:27 UTC, filipsobol commented on packages/core/docs/integrate/cache-driver.md
> +If you want to integrate with Vue Storefront, please **contact the core team on our [discord](https://discord.vuestorefront.io)** first. We are eager to help you with building it and ensuring its hig
```suggestion
If you want to integrate with Vue Storefront, please **contact the core team on our [Discord](https://discord.vuestorefront.io)** first. We are eager to help you with building it and ensuring its high quality! Building the integration together with the core team is the best way to keep its quality high and make it officially recommended once it's done.
```

2021-04-26 09:27 UTC, filipsobol commented on packages/core/docs/integrate/cms.md
> +If you want to integrate with Vue Storefront, please **contact the core team on our [discord](https://discord.vuestorefront.io)** first. We are eager to help you with building it and ensuring its hig
```suggestion
If you want to integrate with Vue Storefront, please **contact the core team on our [Discord](https://discord.vuestorefront.io)** first. We are eager to help you with building it and ensuring its high quality! Building the integration together with the core team is the best way to keep its quality high and make it officially recommended once it's done.
```

2021-04-26 09:27 UTC, filipsobol commented on packages/core/docs/integrate/integration-guide.md
> +If you want to integrate with Vue Storefront, please **contact the core team on our [discord](https://discord.vuestorefront.io)** first. We are eager to help you with building it and ensuring its hig
```suggestion
If you want to integrate with Vue Storefront, please **contact the core team on our [Discord](https://discord.vuestorefront.io)** first. We are eager to help you with building it and ensuring its high quality! Building the integration together with the core team is the best way to keep its quality high and make it officially recommended once it's done.
```

2021-04-26 09:27 UTC, filipsobol commented on packages/core/docs/shopify/maintainers.md
> +  discord="yogeshsuhagiya"
```suggestion
  discord="viralr07#1995"
```

2021-04-26 09:28 UTC, filipsobol commented
Thank you for this contribution. I added few suggestions

2021-04-27 15:57 UTC, filrak commented
Wow, that's a lot of work, thanks so much @janmyszkier ❤️

2021-05-07 07:52 UTC, filipsobol commented
Closing due to inactivity. Updating the links will be done in this PR https://github.com/vuestorefront/vue-storefront/pull/5888

2021-05-07 07:52 UTC, closed without merging