Add args parameter to custom queries
vuestorefront/vue-storefront pull request #5854
Opened 2021-04-28 12:14 UTC by andrzejewsky

2021-04-28 16:41 UTC, filrak requested changes

2021-04-28 16:41 UTC, filrak commented on packages/core/docs/guide/composables.md
> +The custom query function always has in the arguments the default query (`query`), default variables (`variables`) and additional parameters (`args`) sent from the front-end. This function always mus
can you add some example with a frontend call and then receiving this in query?

2021-04-29 12:52 UTC, filrak commented on packages/core/docs/guide/composables.md
> +        'my-products-query': ({ query, variables, metadata }) => {
make something more generic

2021-04-29 12:53 UTC, filrak commented on packages/core/docs/guide/composables.md
> +        'my-products-query': ({ query, variables, metadata }) => {
`metaData` ?

2021-04-29 12:54 UTC, filrak approved these changes

2021-04-29 13:04 UTC, merged

2021-04-29 13:08 UTC, filipsobol commented
Docs look fine :thumbsup: