Read i18n from cookies on midddleware
vuestorefront/vue-storefront pull request #5919
Opened 2021-05-17 13:28 UTC by andrzejewsky

Redding locales, currencies and country from incoming cookies instead of config file in middleware.

2021-05-19 07:39 UTC, filrak requested changes
Shouldn't we remove `country` and `currency` from middleware config then?

Also can you update https://docs.vuestorefront.io/v2/commercetools/configuration.html#middleware-commercetools-configuration accordingly?

2021-05-19 08:06 UTC, filipsobol commented
@andrzejewsky Please update [Intternationalization doc](https://docs.vuestorefront.io/v2/advanced/internationalization.html) to reflect the changes. I can review and, if necessary, edit it.

2021-05-20 08:45 UTC, andrzejewsky commented
@filipsobol @filrak the old properties are still supported, we can't just remove them - for some users the old behavior can be the one they use. I added support i18n by cookies, but the old way still work

2021-05-20 10:32 UTC, filipsobol requested changes

2021-05-20 10:32 UTC, filipsobol commented on packages/core/docs/commercetools/configuration.md
> +By default the i18n settings, such as `currency`, `locale` and `country` are loaded from cookies. To force and override that behavior you can also set those properties under the `api` section.
Please add an example

2021-05-20 10:32 UTC, filipsobol commented on packages/core/docs/commercetools/configuration.md
> +By default the i18n settings, such as `currency`, `locale` and `country` are loaded from cookies. To force and override that behavior you can also set those properties under the `api` section.
```suggestion
By default, the internationalization settings, such as `currency`, `locale`, and `country` are loaded from cookies. To override this behavior you can set those properties inside the `api` configuration.
```

2021-05-20 11:39 UTC, merged