docs-#5963: add custom query example to docs
vuestorefront/vue-storefront pull request #5964
Opened 2021-06-01 18:38 UTC by Baroshem

### Related Issues

closes #5963 

### Short Description of the PR

### Screenshots of Visual Changes before/after (if There Are Any)

### Pull Request Checklist

- [ ] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [ ] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- I tested manually my code and it works well with both:
- [ ] Default Theme
- [ ] Capybara Theme
- [ ] I have written test cases for my code

- [ ] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

2021-06-02 06:36 UTC, Fifciu approved these changes

2021-06-02 07:50 UTC, filrak requested changes
Can we also move whole custom queries section to a new "Extending GraphQL Queries" doc in "Advanced" ?

It's hidden too deep for now

2021-06-04 08:03 UTC, Baroshem commented
@filrak 

Moved custom query to a separate document. Now it should be easier to find.

2021-06-08 09:54 UTC, andrzejewsky approved these changes

2021-06-08 10:33 UTC, filipsobol commented on packages/core/docs/advanced/extending-graphql-queries.md
> +module.exports = {
```suggestion
// middleware.config.js

module.exports = {
```

2021-06-08 10:34 UTC, filipsobol commented on packages/core/docs/advanced/extending-graphql-queries.md
> +module.exports = {
```suggestion
```js
// middleware.config.js

const customQueries = require('./customQueries');

module.exports = {
```

2021-06-08 10:40 UTC, filipsobol commented on packages/core/docs/advanced/extending-graphql-queries.md
> +In case of many custom queries extending the default ones, we recommend extracting them into separate folder to not overload `middleware.config.js` with GraphQL queries:
```suggestion
## Keeping the configuration tidy

Your configuration file can quickly become a mess if you override a lot of queries. We recommend extracting them into a separate folder to not overload `middleware.config.js` with GraphQL queries.

You can create a new file (or files) that exports the queries. Then, you can import them in the `middleware.config.js`:
```

2021-06-08 11:24 UTC, merged