Bugfix/product deletion #5974
vuestorefront/vue-storefront pull request #5975
Opened 2021-06-08 09:41 UTC by SergeyDarnopykh

### Related Issues

closes #5974

### Short Description of the PR
Fix the issue of product deletion from cart on logout->login on "out of stock" error

### Screenshots of Visual Changes before/after (if There Are Any)

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [x] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- I tested manually my code and it works well with both:
- [x] Default Theme
- [x] Capybara Theme
- [x] I have written test cases for my code

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

2021-06-08 09:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5975) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5975) before we can accept your contribution.<br/><hr/>**sergeyDarn** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/vue-storefront?pullRequest=5975) it.</sub>

2021-06-21 09:45 UTC, lukaszjedrasik reviewed
Please resolve conflict and then we can merge your PR 🚀

2021-06-22 07:40 UTC, lukaszjedrasik approved these changes

2021-06-28 07:46 UTC, Fifciu requested changes

2021-06-28 07:46 UTC, Fifciu commented on core/modules/cart/store/actions/quantityActions.ts
> +      Logger.log('Restoring qty after error' + product.sku + ' ' + prevQty, 'cart', )()
```suggestion
      Logger.log('Restoring qty after error ' + product.sku + ' ' + prevQty, 'cart')()
```

2021-06-28 09:50 UTC, SergeyDarnopykh commented on core/modules/cart/store/actions/quantityActions.ts
> +      Logger.log('Restoring qty after error' + product.sku + ' ' + prevQty, 'cart', )()
✅

2021-07-06 14:39 UTC, Fifciu approved these changes

2021-07-06 14:39 UTC, Fifciu commented
Good job @SergeyDarnopykh, thanks!

2021-07-06 14:40 UTC, merged