Allow to configure the list of ElasticSearch indices
vuestorefront/vue-storefront pull request #5979
Opened 2021-06-09 12:07 UTC by SergeyDarnopykh

### Related Issues

closes #5978

### Short Description of the PR
Allow to configure the list of ElasticSearch indices (to be able to add custom ones)

### Screenshots of Visual Changes before/after (if There Are Any)

### Pull Request Checklist

- [x] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [x] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [x] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- I tested manually my code and it works well with both:
- [x] Default Theme
- [x] Capybara Theme
- [x] I have written test cases for my code

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

2021-06-21 09:50 UTC, lukaszjedrasik requested changes

2021-06-21 09:50 UTC, lukaszjedrasik commented on config/default.json
> +    "indices": ["product", "attribute", "category", "taxrule", "review", "cms_page", "cms_block", "cms_hierarchy"],
```suggestion
    "indices": [
       "product", 
       "attribute", 
       "category", 
       "taxrule", 
       "review", 
       "cms_page", 
       "cms_block", 
       "cms_hierarchy"
     ],
```

2021-06-21 09:50 UTC, lukaszjedrasik commented on docs/guide/data/entity-types.md
> +    "indices": ["product", "attribute", "category", "taxrule", "review", "cms_page", "cms_block", "cms_hierarchy"],
```suggestion
    "indices": [
       "product", 
       "attribute", 
       "category", 
       "taxrule", 
       "review", 
       "cms_page", 
       "cms_block", 
       "cms_hierarchy"
     ],
```

2021-06-22 07:45 UTC, SergeyDarnopykh commented on config/default.json
> +    "indices": ["product", "attribute", "category", "taxrule", "review", "cms_page", "cms_block", "cms_hierarchy"],
✅

2021-06-22 07:45 UTC, SergeyDarnopykh commented on docs/guide/data/entity-types.md
> +    "indices": ["product", "attribute", "category", "taxrule", "review", "cms_page", "cms_block", "cms_hierarchy"],
✅

2021-06-22 08:47 UTC, lukaszjedrasik approved these changes

2021-06-22 10:24 UTC, Fifciu requested changes
Great job. But let's rename `indices` to `entityTypes`

2021-06-22 10:24 UTC, Fifciu commented on config/default.json
> +    "indices": [
Let's call them `entityTypes`

2021-06-22 11:26 UTC, SergeyDarnopykh commented on config/default.json
> +    "indices": [
✅

2021-06-24 08:58 UTC, Fifciu requested changes
Looks great, now please add info about necessity of adding `entityTypes` property to the Upgrade notes

2021-06-25 07:26 UTC, SergeyDarnopykh commented
> Looks great, now please add info about necessity of adding `entityTypes` property to the Upgrade notes

I'm not 100% that's what you meant, but I added the information about elastic entity types to `docs/guide/upgrade-notes/README.md`  into `1.12 -> 1.13` section. If it's not what you meant, let me know and I will change it.

2021-06-25 12:13 UTC, Fifciu requested changes
We've just synced develop with 1.12.3 after patch release. Please resolve conflict, then I can merge

2021-06-28 07:32 UTC, Fifciu approved these changes

2021-06-28 07:37 UTC, Fifciu commented
Great job, thanks

2021-06-28 07:37 UTC, merged