Update Adyen Doc
vuestorefront/vue-storefront pull request #5993
Opened 2021-06-14 13:24 UTC by Fifciu

Updated Adyen Doc

2021-06-14 13:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5993) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=5993) before we can accept your contribution.<br/><hr/>**Fifciuu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/vue-storefront?pullRequest=5993) it.</sub>

2021-06-14 13:34 UTC, Baroshem approved these changes
I wasn't added as a reviewer but I really like content. When implementing Adyen I might probably run into similar problems so having straight answer to the question is a big 👍

2021-06-14 13:34 UTC, Baroshem reviewed
I wasn't added as a reviewer but I really like content. When implementing Adyen I might probably run into similar problems so having straight answer to the question is a big 👍

2021-06-14 13:48 UTC, filipsobol requested changes

2021-06-14 13:48 UTC, filipsobol commented on packages/core/docs/integrations/adyen.md
> +Open browser's `Network` tab. Each request related to the payment will have Commercetools Payment object in the response. You could look at `custom.fields.SOME_FIELD` to discover what has been sent t
```suggestion

### How to debug data flow?

Open the` Network` tab in the browser's devtools. Each payment request will have commercetools [Payment object](https://docs.commercetools.com/api/projects/payments#payment) in the response. You can check `custom.fields.SOME_FIELD` to see what has data was sent to Adyen and what was the response (or error).

```

2021-06-14 13:48 UTC, filipsobol commented on packages/core/docs/integrations/adyen.md
> +Open browser's `Network` tab. Each request related to the payment will have Commercetools Payment object in the response. You could look at `custom.fields.SOME_FIELD` to discover what has been sent t
Please specify what `custom.fields.SOME_FIELD` is. This name is not used anywhere else in this document.

2021-06-14 13:48 UTC, filipsobol commented on packages/core/docs/integrations/adyen.md
> +It can work properly only on provided `origin`.
```suggestion
### 3DS2 Auth doesn't work in one environment

There might be a situation when you can finish 3DS2 Auth in the local environment but not in the other, like staging. When this happens, make sure to change `origin` in the `middleware.config.js` from `http://localhost:3000` to the URL of your staging environment. 
```

2021-06-14 13:48 UTC, filipsobol commented on packages/core/docs/integrations/adyen.md
> +Update version of the both extension module and notification module. Just modify tag to the newest version in `extension.Dockerfile` and `notification.Dockerfile`.
```suggestion

Update extension and notification modules to the newest version by updating the tag in `extension.Dockerfile` and `notification.Dockerfile`.

```

2021-06-14 13:48 UTC, filipsobol commented on packages/core/docs/integrations/adyen.md
> +Update version of the both extension module and notification module. Just modify tag to the newest version in `extension.Dockerfile` and `notification.Dockerfile`.
I suggest being more precise with the work `newest` since it might be different in the future. If you think it's okay, we can leave it.

2021-06-15 06:28 UTC, filipsobol requested changes

2021-06-16 08:51 UTC, filipsobol approved these changes

2021-06-16 09:57 UTC, merged