Refactor: Switch places between state and country inputs in shipping form
vuestorefront/vue-storefront pull request #6071
Opened 2021-07-13 11:50 UTC by lsliwaradioluz

### Short Description of the PR

Currently in our checkout form, the **State** input comes before the **Country** input despite the former depends on the latter. This way - whenever you choose your country - you have to switch back to **State** manually and then jump over to ZIP-code. 

### Screenshots of Visual Changes before/after (if There Are Any)

Before:
![image](https://user-images.githubusercontent.com/39009379/125446631-642e57af-4567-4c2b-907b-ac8b7464aaa8.png)

After:
![image](https://user-images.githubusercontent.com/39009379/125446703-32f45f65-8d3b-4e94-a8e8-b68db2f1ac26.png)

2021-07-13 11:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=6071) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=6071) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/vue-storefront?pullRequest=6071) it.</sub>

2021-07-14 06:48 UTC, Baroshem approved these changes

2021-08-06 08:57 UTC, Baroshem requested changes

2021-08-06 08:57 UTC, Baroshem commented on packages/commercetools/theme/components/MyAccount/BillingAddressForm.vue
> +            label="Country"
i18n

2021-08-06 08:57 UTC, Baroshem commented on packages/commercetools/theme/components/MyAccount/BillingAddressForm.vue
> +          :rules="`required|oneOf:${countries.map(c => c.name).join(',')}`"
Let's create a rule out of it. It will be easier to understand the logic of a rule when it will be in script tag rather than in the template

2021-08-06 08:57 UTC, Baroshem commented on packages/commercetools/theme/components/MyAccount/ShippingAddressForm.vue
> +            label="Country"
i18n

2021-08-06 08:57 UTC, Baroshem commented on packages/commercetools/theme/components/MyAccount/ShippingAddressForm.vue
> +          :rules="`required|oneOf:${countries.map(c => c.name).join(',')}`"
Same here with rule. Move to the script tag

2021-08-06 08:57 UTC, Baroshem commented on packages/commercetools/theme/pages/Checkout/Billing.vue
> +            label="Country"
i18n

2021-08-06 08:57 UTC, Baroshem commented on packages/commercetools/theme/pages/Checkout/Billing.vue
> +            label="State/Province"
i18n

2021-08-06 08:57 UTC, Baroshem commented on packages/commercetools/theme/pages/Checkout/Shipping.vue
> +            label="Country"
i18n

2021-08-06 08:57 UTC, Baroshem commented on packages/commercetools/theme/pages/Checkout/Shipping.vue
> +            label="State/Province"
i18n

2021-08-06 10:10 UTC, Baroshem approved these changes
![4xll63](https://user-images.githubusercontent.com/37120330/128494979-3d2dcf93-ea67-4ea0-8c50-b4bb62d81c76.png)

2021-08-06 10:29 UTC, justyna-13 approved these changes
Please add changelog file :slightly_smiling_face:

2021-08-06 10:36 UTC, lsliwaradioluz commented
@justyna-13 Done ✔️

2021-08-06 10:36 UTC, merged