refactor: updates form validation scheme for street, number and city
vuestorefront/vue-storefront pull request #6122
Opened 2021-07-26 18:56 UTC by bloodf

### Related Issues

closes #6010 (Jira)[https://vsf.atlassian.net/browse/OS-117]
closes #5976 (Jira)[https://vsf.atlassian.net/browse/OS-127]

### Short Description of the PR
update the current validation rules to a more broad one, where it validates the requirement of the filed only, due to some street names, numbers, or cities having different amounts of characters.

fixes the validation not being applied correctly in the apartment number form input

### Screenshots of Visual Changes before/after (if There Are Any)

### Pull Request Checklist

- [ ] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [ ] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- I tested manually my code and it works well with both:
- [ ] Default Theme
- [ ] Capybara Theme
- [ ] I have written test cases for my code

- [ ] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

2021-07-27 06:15 UTC, Baroshem approved these changes

2021-07-27 07:56 UTC, filipsobol requested changes
Can you also update components in the `packages/commercetools/theme/pages/Checkout` folder?

This will require an additional changelog file in the `packages/core/docs/commercetools/changelog` folder (you can copy the one you already created).

2021-07-27 18:39 UTC, bloodf commented
> Can you also update components in the `packages/commercetools/theme/pages/Checkout` folder?
> 
> This will require an additional changelog file in the `packages/core/docs/commercetools/changelog` folder (you can copy the one you already created).

The code on the theme for `commercetools` was already updated.

I've added the changelog

2021-07-28 08:06 UTC, filipsobol approved these changes

2021-07-28 15:38 UTC, merged