Sync next
vuestorefront/vue-storefront pull request #6166
Opened 2021-08-05 16:37 UTC by Baroshem

### Related Issues

closes #

### Short Description of the PR

### Screenshots of Visual Changes before/after (if There Are Any)

### Pull Request Checklist

- [ ] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.
- [ ] I have tested my Pull Request on production build and (to my knowledge) it works without any issues

- I tested manually my code and it works well with both:
- [ ] Default Theme
- [ ] Capybara Theme
- [ ] I have written test cases for my code

- [ ] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

2021-08-05 16:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=6166) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=6166) before we can accept your contribution.<br/>**9** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: andrzejewsky<br/>:white_check_mark: Fifciu<br/>:white_check_mark: lukasborawski<br/>:white_check_mark: filipsobol<br/>:white_check_mark: filrak<br/>:white_check_mark: lukaszjedrasik<br/>:white_check_mark: igorwojciechowski<br/>:white_check_mark: Baroshem<br/>:white_check_mark: AdamPawlinski<br/>:x: Fifciuu<br/><hr/>**Fifciuu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/vue-storefront?pullRequest=6166) it.</sub>

2021-08-06 06:30 UTC, Mateuszpietrusinski commented on packages/core/nuxt-module/lib/module.js
>  module.exports = function VueStorefrontNuxtModule (moduleOptions) {
Just asking why `lib` folder is included in the repo?

2021-08-06 06:33 UTC, Mateuszpietrusinski requested changes
Most of the files LGTM, but I saw that this pr includes changes inside `lib` folder in `nuxt-module` package, let me know is it know behavior?

2021-08-06 06:33 UTC, Mateuszpietrusinski commented on packages/core/nuxt-module/lib/plugins/context.js
> +import { configureContext } from '@vue-storefront/core';
same as above

2021-08-06 06:56 UTC, Mateuszpietrusinski commented
Ok after analyze I realize that those fields are added to the repository in Feb 2020 so let's leave them in peace.

2021-08-06 06:56 UTC, Mateuszpietrusinski approved these changes

2021-08-06 07:56 UTC, Fifciu approved these changes

2021-08-06 07:57 UTC, Fifciu commented
LGTM

2021-08-06 08:43 UTC, igorwojciechowski approved these changes

2021-08-06 08:50 UTC, merged