Added e2e tests for breadcrumbs
vuestorefront/vue-storefront pull request #6267
Opened 2021-09-02 14:55 UTC by dawid-ziobro

## Description

Added missing e2e tests for breadcrumbs for category page.

## Related Issue

Closes #6253 

## How Has This Been Tested?

Automatic e2e tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

#### Changelog
- [ ] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.

#### Tests
- [ ] I have written test cases for my code
- [ ] I have tested my Pull Request on production build and (to my knowledge) it works without any issues
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

#### Code standards
- [x] My code follows the code style of this project.

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

#### Docs
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-09-03 12:52 UTC, igorwojciechowski approved these changes

2021-09-03 13:33 UTC, bloodf approved these changes

2021-09-07 11:39 UTC, igorwojciechowski requested changes

2021-09-07 11:39 UTC, igorwojciechowski commented on packages/commercetools/theme/tests/e2e/integration/e2e-breadcrumbs.spec.ts
> +context('Breadcrumbs', () => {
```suggestion
context(['regression], 'Breadcrumbs', () => {
```
Please add 'regression' tag to context :)

2021-09-07 11:44 UTC, igorwojciechowski requested changes

2021-09-07 11:44 UTC, igorwojciechowski commented on packages/commercetools/theme/tests/e2e/integration/e2e-breadcrumbs.spec.ts
> +context(['regression], 'Breadcrumbs', () => {
```suggestion
context(['regression'], 'Breadcrumbs', () => {
```
: >

2021-09-08 10:48 UTC, igorwojciechowski approved these changes

2021-09-08 10:52 UTC, merged