fix(ct): fix exception directly entering checkout payment url
vuestorefront/vue-storefront pull request #6288
Opened 2021-09-08 10:54 UTC by RafalDobrowolski

## Related Issue

Closes #5983

## How Has This Been Tested?

Automatic e2e tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.

#### Changelog
- [ ] I have updated the Changelog ([V1](https://github.com/DivanteLtd/vue-storefront/blob/develop/CHANGELOG.md)) [v2](https://docs-next.vuestorefront.io/contributing/creating-changelog.html) and mentioned all breaking changes in the public API.
- [ ] I have documented all new public APIs and made changes to existing docs mentioning the parts I've changed so they're up to date.

#### Tests
- [x] I have written test cases for my code
- [ ] I have tested my Pull Request on production build and (to my knowledge) it works without any issues
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

#### Code standards
- [x] My code follows the code style of this project.

- [x] I have followed [naming conventions](https://github.com/kettanaito/naming-cheatsheet)

#### Docs
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-09-08 10:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=6288) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vuestorefront/vue-storefront?pullRequest=6288) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vuestorefront/vue-storefront?pullRequest=6288) it.</sub>

2021-09-08 11:11 UTC, lukaszjedrasik reviewed
Please add changelog: https://docs.vuestorefront.io/v2/contributing/creating-changelog.html

2021-09-08 11:12 UTC, Fifciu commented
What if I have an active cart and jump directly to the payment step via URL? I did not fill shipping information, am I able to place an order?

2021-09-08 12:59 UTC, RafalDobrowolski commented
> What if I have an active cart and jump directly to the payment step via URL? I did not fill shipping information, am I able to place an order?
I think, there is no possibility place an order, because is available only from the payment step , but if you don't fill out shipping and billing address and try jump directly to the payment step via URL, you redirect to the home page.

2021-09-08 13:35 UTC, lukaszjedrasik approved these changes

2021-09-08 15:04 UTC, igorwojciechowski requested changes

2021-09-08 15:04 UTC, igorwojciechowski commented on packages/commercetools/theme/tests/e2e/integration/e2e-checkout-payment-validation.spec.ts
> +    expect(page.home.path).to.be.eq(data.homePath);
```suggestion
    cy.url().should('equal', Cypress.config.baseUrl)
```
Should be something like that. Cuz as it is, we don't compare the actual URL, but hardcoded values.

2021-09-08 15:05 UTC, igorwojciechowski commented on packages/commercetools/theme/tests/e2e/integration/e2e-checkout-payment-validation.spec.ts
> +    expect(page.home.path).to.be.eq(data.homePath);
Also, test data for this case can be removed after

2021-09-09 12:41 UTC, igorwojciechowski approved these changes

2021-09-10 14:57 UTC, dawid-ziobro approved these changes

2021-09-14 14:05 UTC, merged